projectmanagement/projectmanagement/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todolist/', include('todolist.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

projectmanagement/todolist/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login-email',views.user_login,name='user_login'),
    url(r'^register-user',views.register_user,name='register_user'),
    url(r'^registration-page',views.registration_page,name='registration_page'),
    url(r'^logout',views.user_logout,name='user_logout'),
    url(r'^task/',views.task_details,name='task_details'), 
    url(r'^change-task-status/',views.change_task_status,name='change_task_status'), 
    url(r'^delete-task/',views.delete_task,name='delete_task'), 
    url(r'^edit-task/',views.edit_task,name='edit_task'), 
    url(r'^create-task/',views.create_task,name='create_task'), 
]

projectmanagement/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=1000, null=True)
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateTimeField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todo_created_by', on_delete=models.CASCADE)

# Table to track any changes in status of tasks
class TaskStatus(models.Model):
    user = models.ForeignKey(User, related_name='task_status_changed_by', on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    status_change_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='task_status_changed_by', on_delete=models.CASCADE)

projectmanagement/todolist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from models import Task, TaskStatus
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from django.utils.timezone import now

# Function which renders user registration page where you can create new users
def registration_page(request):
    context = {}
    user = request.user
    if not str(user) == 'AnonymousUser':
        msg = [{'text': 'Please <a href="/todolist/logout">logout</a> and then visit <a href="/todolist/registration-page">registration page</a> to create user', 'level':'danger', 'code':120, 'persistent':True}]
        context['user_logged_in'] = True
        context['messages'] = msg
        return render(request, 'todolist/register_user.html', context)
    return render(request, 'todolist/register_user.html', context)

# Function which registers new users on the platform
def register_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    context = {}

    if User.objects.filter(username=username).exists():
        msg = [{'text': 'This Username is already taken. Please specify a different Username', 'level':'danger', 'code':120, 'persistent':True}]
    else:
        user = User.objects.create_user(username, '', password)
        msg = [{'text': 'Successfully registered the user. Please go to <a href="/todolist">Login page</a> to start creating tasks', 'level':'success', 'persistent':True}]
    
    context['messages'] = msg
    return render(request, 'todolist/register_user.html', context)
    
#Function which helps to authenticate user and log them in
@csrf_exempt
def user_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = User.objects.filter(username=username)
    auth_user = authenticate(username=username, password=password)
    if auth_user is not None:
        if auth_user.is_active:
            login(request, auth_user)
            # return home(request)
            return HttpResponseRedirect('/todolist')
    else:
        context = {}
        msg = [{'text': 'Please enter valid username and password', 'level':'danger', 'code':120, 'persistent':True}]
        context['messages'] = msg
        return render(request, 'todolist/login.html', context)

# Function which helps to logout the user
def user_logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/todolist')

# Function which displays the list of tasks (Completed and Pending tasks)
def index(request):
    user = request.user
    if str(user) == 'AnonymousUser':
        return render(request, 'todolist/login.html')
    context = {}
    user = User.objects.get(username='user1')
    context['tasks'] = Task.objects.all()
    context['all_users'] = User.objects.all()
    return render(request, 'todolist/index.html', context)

# Function which displays individual task details
def task_details(request):
    current_user = request.user
    context = {}
    task_id = request.GET.get('task_id')
    task_obj = Task.objects.get(id=task_id)
    context['task'] = task_obj
    track_list = 'Created by ' + task_obj.created_by.username + ' on ' + task_obj.created_date.strftime('%Y-%m-%d %H:%M')
    for change_status in TaskStatus.objects.filter(task=task_obj).order_by('status_change_date'):
        if change_status.completed:
            track_list += ' --> Closed by ' + change_status.user.username + ' on ' + change_status.status_change_date.strftime('%Y-%m-%d %H:%M')
        else:
            track_list += ' --> Reopened by ' + change_status.user.username + ' on ' + change_status.status_change_date.strftime('%Y-%m-%d %H:%M')

    context['track_list'] = track_list
    print 'track_list = ', track_list
    if task_obj.created_by == current_user:
        context['is_current_user_task'] = True
    else:
        context['is_current_user_task'] = False
    return render(request, 'todolist/task_details.html', context)

# Function which  changes the task staus to completed or pending
def change_task_status(request):
    current_user = request.user
    task_id = request.GET.get('task_id')
    task_obj = Task.objects.get(id=task_id)
    task_status = TaskStatus.objects.create(task=task_obj, user=current_user)
    if task_obj.completed:
        task_obj.completed = False
        task_obj.completed_date = None
        task_status.completed = False
    else:
        task_obj.completed = True
        task_obj.completed_date = now()
        task_status.completed = True
    task_obj.save()
    task_status.save()
    return HttpResponseRedirect('/todolist')

# Function which deletes a task 
def delete_task(request):
    current_user = request.user
    task_id = request.GET.get('task_id')
    task_obj = Task.objects.get(id=task_id)
    if task_obj.created_by == current_user:
        task_obj.delete()
        return HttpResponseRedirect('/todolist')

# Function which saves the edited task 
def edit_task(request):
    current_user = request.user
    task_id = request.POST.get('task_id')
    edited_title = request.POST.get('edited_title')
    edited_description = request.POST.get('edited_description')
    task = Task.objects.get(id=task_id)
    task.title = edited_title
    task.description = edited_description
    task.save()
    return HttpResponseRedirect('/todolist')

# Function which creates new tasks
def create_task(request):
    current_user = request.user
    title = request.POST.get('title')
    description = request.POST.get('description')
    task = Task.objects.create(title=title, description=description, created_by=current_user)
    return HttpResponseRedirect('/todolist')

projectmanagement/todolist/templates/todolist/index.html
<html lang="en">

	<head>

		<meta charset="utf-8">


		<title>Task Management System - Tasks</title>

		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> <!-- for jquery -->

		<script type= "text/javascript">
		    $(document).on('click', '#AddTaskButton', function() {
		    	$('#add_task_form').show()
		    });

		    $(document).on('click', '#cancel_create_task', function() {
		    	$('#add_task_form').hide()
		    });

		    $(document).on('click', '#hide_completed_tasks', function() {
		    	if ($('#hide_completed_tasks').text() == 'Hide completed tasks'){
		    		$('.completed').hide()
		    		$('#hide_completed_tasks').text('Show all tasks') 
		    	}
		    	else{
		    		$('.completed').show()
		    		$('#hide_completed_tasks').text('Hide completed tasks') 
		    	}
		    });

		</script>

	</head>

	<body>

		<header>

			<!-- Fixed navbar -->
			<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"> 
				<a class="navbar-brand" href="/todolist">Energy Labs Task Management System</a>
					<div class="collapse navbar-collapse" id="navbarCollapse">
						<ul class="navbar-nav mr-auto">

							<li class="nav-item"><a href="/todolist/logout/" class="nav-link">Log Out</a></li>

						</ul>
					</div>
			</nav>
		</header>

		<!-- Begin page content -->
		<main role="main" class="container" style="padding: 72px 15px 0;">

		  
			<button class="btn btn-primary" id="AddTaskButton" type="button"
			  data-toggle="collapse" data-target="#AddEditTask">Add task</button>

			{% if tasks %}
				<button class="btn btn-primary" id="hide_completed_tasks" type="button"
			 		data-toggle="collapse" style="float:right">Hide completed tasks</button>
			{% endif %}


			  <br>
			  <br>


			<form action="/todolist/create-task/" method="post" id='add_task_form' style="display:none">
			  	{% csrf_token %}

			    <div class="form-group">
					<p>
						<label for="id_title">Title:</label>
						<input class="form-control" type="text" name="title" autofocus="" maxlength="254" required="" id="title" placeholder="Title of the task">
					</p>
			    </div>

			    <div class="form-group">
					<p>
						<label for="id_description">Description:</label>
						<textarea class="form-control" type="text" name="description" required="" id="description" placeholder="Description of the task"></textarea>
					</p>
			    </div>

			    <button type="submit" class="btn btn-primary">Submit</button>
			    <button id="cancel_create_task" class="btn btn-success" style="margin-left:12px">Cancel</button>
			</form>

			{% if tasks %}

				<table class="table" id="tasktable">
				    <tr class="nodrop">
						<th>Task</th>
						<th>Created</th>
						<th>Created by</th>
						<th>Status</th>
				    </tr>

				    {% for task in tasks %}
						<tr id="{{ task.id }}" class="{% if task.completed %} completed {% else %} pending {% endif %}">
							<td>
								<a href="/todolist/task?task_id={{task.id}}">{{ task.title|truncatewords:10 }}</a>
							</td>
							<td>
								{{ task.created_date|date:"m/d/Y" }}
							</td>
							<td>
								{{ task.created_by }}
							</td>
							<td>
								<button class="btn btn-info btn-sm" disabled>
									{% if task.completed %}
									Completed
									{% else %}
									Pending
									{% endif %}
								</button>
							</td>
						</tr>
				    {% endfor %}
				  </table>

		    {% endif %}


		</main>



	</body>
</html>

projectmanagement/todolist/templates/todolist/login.html
<html lang="en">

    <head>

        <meta charset="utf-8">


        <title>Task Management System - Login</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    

    </head>

    <body>

        <header>
          <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"> 
                <a class="navbar-brand" href="/todolist">Energy Labs Task Management System</a>
            </nav>
        </header>

        <!-- Begin page content -->
        <main role="main" class="container" style="padding: 72px 15px 0;">

          
            <h3>Sign In</h3>

            {% if messages %} <!-- Displays warning messages when wrong username/password entered -->       
                {% for message in messages %}
                    <div class="alert alert-danger" role= "alert">{{ message.text }}</div>
                {% endfor %}
            {% endif %}

            <form action="/todolist/login-email/" method="post"> {% csrf_token %}

                <div class="form-group">
                  <p>
                    <label for="id_username">Username:</label>
                    <input class="form-control" type="text" name="username" autofocus="" maxlength="254" required="" id="id_username" placeholder="Username">
                  </p>
                </div>

                <div class="form-group">
                  <p>
                    <label for="id_password">Password:</label>
                    <input class="form-control" type="password" name="password" required="" id="id_password" placeholder="Password">
                  </p>
                </div>

                <button type="submit" class="btn btn-primary">Login</button> or
                <a href='/todolist/registration-page' class="btn btn-success">Signup</a>

            </form>


        </main>



    </body>

</html>

projectmanagement/todolist/templates/todolist/register_user.html
<html lang="en">

    <head>

        <meta charset="utf-8">


        <title>Task Management System - Register</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    

    </head>

    <body>

        <header>
          <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"> 
                <a class="navbar-brand" href="/todolist">Energy Labs Task Management System</a>
            </nav>
        </header>

        <!-- Begin page content -->
        <main role="main" class="container" style="padding: 72px 15px 0;">

          
            <h3>Register</h3>

            {% if messages %} <!-- Displays warning messages when wrong username/password entered -->       
                {% for message in messages %}
                    <div class="alert alert-danger" role= "alert">{{ message.text|safe }}</div>
                {% endfor %}
            {% endif %}

            {% if not user_logged_in %}

                <form action="/todolist/register-user/" method="post"> {% csrf_token %}

                    <div class="form-group">
                      <p>
                        <label for="id_username">Username:</label>
                        <input class="form-control" type="text" name="username" autofocus="" maxlength="254" required="" id="id_username" placeholder="Username">
                      </p>
                    </div>

                    <div class="form-group">
                      <p>
                        <label for="id_password">Password:</label>
                        <input class="form-control" type="password" name="password" required="" id="id_password" placeholder="Password">
                      </p>
                    </div>

                    <button type="submit" class="btn btn-primary">Register</button> or
                    <a href='/todolist' class="btn btn-success">Login if you already have an account</a>
                </form>

            {% endif %}


        </main>



    </body>

</html>

projectmanagement/todolist/templates/todolist/task_details.html
<html lang="en">

	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> <!-- for jquery -->

	    <meta charset="utf-8">
	    

	    <title>Task Management System - Tasks</title>

	    <!-- Bootstrap core CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    


		<script type= "text/javascript">
		    $(document).on('click', '#edit_task', function() {
		    	$('#edit_form').show()
		    });

		</script>

	</head>

	<body>
		
		<header>

			<!-- Fixed navbar -->
			<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"> 
				<a class="navbar-brand" href="/todolist">Energy Labs Task Management System</a>
				
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav mr-auto">

					  <li class="nav-item"><a href="/todolist/logout/" class="nav-link">Log Out</a></li>

					</ul>
				</div>
			
			</nav>

		</header>


		<!-- Begin page content -->
		<main role="main" class="container" style="padding: 72px 15px 0;">
			<div class="row">
			    <div class="col-sm-8">
					<h3 class="task-title" id='title'>{{ task.title }}</h3>
					{% if task.description or track_list %}
						<p class="task-description" id='description'>{{ task.description }} <br> <br><b>Track List</b><br> {{ track_list }}</p>
					{% endif %}

					<form action="/todolist/edit-task/" method="post" id='edit_form' style="display:none">
						{% csrf_token %}
						<div class="form-group">
							<p>
								<label for="id_title">Title:</label>
								<input class="form-control" type="text" name="edited_title" autofocus="" maxlength="254" required="" id="edited_title" placeholder="Title" value="{{ task.title }}">
							</p>
						</div>
						<div class="form-group">
							<p>
								<label for="id_description">Description:</label>
								<textarea class="form-control" type="text" name="edited_description" id="edited_description" placeholder="Password">{{ task.description }}</textarea>
							</p>
						</div>
						<div class="form-group" style='display:none'> <!--To identify task we have one hidden form element which holds post id -->
							<p>
								<label for="id_taskid"></label>
								<input class="form-control" type="text" name="task_id" required="" id="task_id" placeholder="Password" value="{{ task.id }}">
							</p>
						</div>
						<button type="submit" class="btn btn-primary">Submit</button>
					</form>

				</div>
			    
			    <div class="col-sm-4">
					<ul class="list-group">
					    <li class="list-group-item">
					      	<form action="" method="post">{% csrf_token %}

					      		{% if is_current_user_task %}

						        	<button class="btn btn-sm btn-primary" id="edit_task" type="button"
						            data-toggle="collapse" data-target="#AddEditTask">Edit Task</button>

						            <a href="/todolist/delete-task?task_id={{task.id}}" class="btn btn-danger btn-sm">Delete</a>

						        {% else %}

						            <a href="/todolist/change-task-status?task_id={{task.id}}" class="btn btn-info btn-sm">
						              {% if task.completed %} Mark Not Done {% else %} Mark Done {% endif %}
						            </a>

					            {% endif %}


					      	</form>
					    </li>

						<li class="list-group-item">
							<strong>Created by:</strong> {{ task.created_by }}
						</li>

						{% if task.completed %}
						  <li class="list-group-item">
								<strong>Completed on:</strong> {{ task.completed_date}}
						  </li>
						{% else %}
						  <li class="list-group-item">
								<strong>Completed:</strong>  {% if task.completed %}Yes{% else %}No{% endif %}
						  </li>
						{% endif %}
					  

					</ul>
			    </div>
		    </div>
		</main>


	</body>
</html>